champion_mapping = {
    'Aatrox': 'Атрокс',
    'Ahri': 'Ари',
    'Akali': 'Акали',
    'Akshan': 'Акшан',
    'Alistar': 'Алистар',
    'Amumu': 'Амуму',
    'Anivia': 'Анивия',
    'Annie': 'Энни',
    'Aphelios': 'Афелий',
    'Ashe': 'Эш',
    'Aurelion Sol': 'Аурелион Сол',
    'Azir': 'Азир',
    'Bard': 'Бард',
    'Bel’Veth': "Бел'Вет",
    'Blitzcrank': 'Блицкранк',
    'Brand': 'Брэнд',
    'Braum': 'Браум',
    'Caitlyn': 'Кейтлин',
    'Camille': 'Камилла',
    'Cassiopeia': 'Кассиопея',
    "Cho'Gath": "Чо'Гат",
    'Corki': 'Корки',
    'Darius': 'Дариус',
    'Diana': 'Диана',
    'Dr. Mundo': 'Доктор Мундо',
    'Draven': 'Дрейвен',
    'Ekko': 'Экко',
    'Elise': 'Элиза',
    'Evelynn': 'Эвелинн',
    'Ezreal': 'Эзреаль',
    'Fiddlesticks': 'Фиддлстикс',
    'Fiora': 'Фиора',
    'Fizz': 'Физз',
    'Galio': 'Галио',
    'Gangplank': 'Гангпланк',
    'Garen': 'Гарен',
    'Gnar': 'Гнар',
    'Gragas': 'Грагас',
    'Graves': 'Грейвз',
    'Gwen': 'Гвен',
    'Hecarim': 'Гекарим',
    'Heimerdinger': 'Хеймердингер',
    'Illaoi': 'Иллаой',
    'Irelia': 'Ирелия',
    'Ivern': 'Иверн',
    'Janna': 'Жанна',
    'Jarvan IV': 'Джарван IV',
    'Jax': 'Джакс',
    'Jayce': 'Джейс',
    'Jhin': 'Джин',
    'Jinx': 'Джинкс',
    "Kai'Sa": "Кай'Са",
    'Kalista': 'Калиста',
    'Karma': 'Карма',
    'Karthus': 'Картус',
    'Kassadin': 'Кассадин',
    'Katarina': 'Катарина',
    'Kayle': 'Кейл',
    'Kayn': 'Каин',
    'Kennen': 'Кеннен',
    "Kha'Zix": "Ка'Зикс",
    'Kindred': 'Киндред',
    'Kled': 'Клед',
    "Kog'Maw": "Ког'Мао",
    'K’Sante': "К'Санте",
    'LeBlanc': 'Ле Блан',
    'Lee Sin': 'Ли Син',
    'Leona': 'Леона',
    'Lillia': 'Лиллия',
    'Lissandra': 'Лиссандра',
    'Lucian': 'Люциан',
    'Lulu': 'Лулу',
    'Lux': 'Люкс',
    'Malphite': 'Мальфит',
    'Malzahar': 'Мальзахар',
    'Maokai': 'Маокай',
    'Master Yi': 'Мастер Йи',
    'Milio': 'Милио',
    'Miss Fortune': 'Мисс Фортуна',
    'Mordekaiser': 'Мордекайзер',
    'Morgana': 'Моргана',
    'Nami': 'Нами',
    'Nasus': 'Насус',
    'Nautilus': 'Наутилус',
    'Neeko': 'Нико',
    'Nidalee': 'Нидали',
    'Nilah': 'Нила',
    'Nocturne': 'Ноктюрн',
    'Nunu & Willump': 'Нуну и Виллумп',
    'Olaf': 'Олаф',
    'Orianna': 'Орианна',
    'Ornn': 'Орн',
    'Pantheon': 'Пантеон',
    'Poppy': 'Поппи',
    'Pyke': 'Пайк',
    'Qiyana': 'Киана',
    'Quinn': 'Квинн',
    'Rakan': 'Рэйкан',
    'Rammus': 'Раммус',
    "Rek'Sai": "Рек'Сай",
    'Rell': 'Релл',
    'Renata Glasc': 'Рената Гласк',
    'Renekton': 'Ренектон',
    'Rengar': 'Ренгар',
    'Riven': 'Ривен',
    'Rumble': 'Рамбл',
    'Ryze': 'Райз',
    'Samira': 'Самира',
    'Sejuani': 'Седжуани',
    'Senna': 'Сенна',
    'Seraphine': 'Серафина',
    'Sett': 'Сетт',
    'Shaco': 'Шако',
    'Shen': 'Шен',
    'Shyvana': 'Шивана',
    'Singed': 'Синджед',
    'Sion': 'Сион',
    'Sivir': 'Сивир',
    'Skarner': 'Скарнер',
    'Sona': 'Сона',
    'Soraka': 'Сорака',
    'Swain': 'Свейн',
    'Sylas': 'Сайлас',
    'Syndra': 'Синдра',
    'Tahm Kench': 'Таам Кенч',
    'Taliyah': 'Талия',
    'Talon': 'Талон',
    'Taric': 'Тарик',
    'Teemo': 'Тимо',
    'Thresh': 'Треш',
    'Tristana': 'Тристана',
    'Trundle': 'Трандл',
    'Tryndamere': 'Триндамир',
    'Twisted Fate': 'Твистед Фэйт',
    'Twitch': 'Твич',
    'Udyr': 'Удир',
    'Urgot': 'Ургот',
    'Varus': 'Варус',
    'Vayne': 'Вейн',
    'Veigar': 'Вейгар',
    "Vel'Koz": "Вел'Коз",
    'Vex': 'Векс',
    'Vi': 'Ви',
    'Viego': 'Виего',
    'Viktor': 'Виктор',
    'Vladimir': 'Владимир',
    'Volibear': 'Волибир',
    'Warwick': 'Варвик',
    'Wukong': 'Вуконг',
    'Xayah': 'Шая',
    'Xerath': 'Зерат',
    'Xin Zhao': 'Ксин Жао',
    'Yasuo': 'Ясуо',
    'Yone': 'Ёнэ',
    'Yorick': 'Йорик',
    'Yuumi': 'Юми',
    'Zac': 'Зак',
    'Zed': 'Зед',
    'Zeri': 'Зери',
    'Ziggs': 'Зиггс',
    'Zilean': 'Зилеан',
    'Zoe': 'Зои',
    'Zyra': 'Зайра',
}


def translate_champion_names(name):
    return champion_mapping.get(name, name)
